
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */


    
public class ALCDETAILS extends javax.swing.JFrame {

    /**
     * Creates new form ALCDETAILS
     */
    public ALCDETAILS() {
        initComponents();
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("FAX NUMBER:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 268, 150, 24);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 460, 53, 27);

        jTextField2.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 102, 102));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 176, 131, 23);

        jTextField3.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 331, 127, 25);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("E-MAIL:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 210, 100, 24);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("NAME:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 104, 120, 24);

        jTextField5.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(590, 104, 120, 25);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("OCCUPATION:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 110, 160, 24);

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("RESIDENTIAL ADDRESS:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(421, 331, 212, 24);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 102, 102));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(421, 377, 208, 101);

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("AADHAR CARD NO.:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(389, 156, 180, 24);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("MOBILE NUMBER:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(15, 330, 170, 24);

        jTextField1.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 104, 131, 25);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("PHONE NUMBER:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(12, 413, 170, 24);

        jTextField4.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(210, 414, 130, 25);

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("PERSONAL MEMORANDA");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(156, 30, 447, 47);

        jTextField6.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 102, 102));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(590, 156, 120, 25);

        jTextField7.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(590, 216, 120, 25);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("CREATE USERNAME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(4, 176, 210, 29);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("CREATE PASSWORD:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(7, 248, 210, 24);

        jTextField8.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jTextField8);
        jTextField8.setBounds(590, 278, 123, 25);

        jPasswordField1.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(212, 249, 130, 25);

        jButton3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(49, 30, 71, 27);

        jLabel.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel.setOpaque(true);
        jLabel.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel);
        jLabel.setBounds(0, -20, 740, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        Citizen c= new Citizen(jTextField1.getText(), jTextField2.getText(), jPasswordField1.getText(), jTextField3.getText(), jTextArea1.getText(), jTextField4.getText(), jTextField5.getText(), jTextField6.getText(), jTextField7.getText(), jTextField8.getText());
        String category="citizen";       
        int i=0;
        
        try{
            i=c.validateInput();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        if(i==1){
            try
            {
                Class.forName("java.sql.DriverManager");
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/JustJustice","root","admin123");
                Statement s=(Statement)con.createStatement();
                String q="insert into citizen values('"+c.getName()+"','"+c.getUname()+"','"+c.getPword()+"','"+c.getMno()+"','"+c.getAddr()+"');";
                String r="insert into citizen2 values('"+c.getUname()+"','"+c.getPhno()+"','"+c.getOcc()+"','"+c.getAdhaarno()+"','"+c.getEmail()+"','"+c.getFaxno()+"');";
                String t="insert into login values('"+c.getUname()+"','"+c.getPword()+"','"+category+"');";
                s.executeUpdate(q);
                s.executeUpdate(r);
                s.executeUpdate(t);
                JOptionPane.showMessageDialog(null,"User Registered!");
            }

            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new HOMEPAGE().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ALCDETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ALCDETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ALCDETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ALCDETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ALCDETAILS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
