
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */

    
    
public class BLOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public BLOGIN() {
        initComponents();
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("LOGIN ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(314, 29, 123, 47);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(161, 241, 190, 32);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 0));
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(158, 313, 200, 32);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 102, 51));
        jRadioButton1.setText("ADVOCATE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(97, 105, 220, 41);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 102, 51));
        jRadioButton2.setText("CITIZEN");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(409, 105, 190, 41);

        jComboBox1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 102, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT DIVISION", "CIVIL", "CRIMINAL" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(215, 158, 244, 38);

        jTextField1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(399, 238, 183, 38);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(221, 374, 87, 27);

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 102));
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(389, 374, 77, 27);

        jPasswordField1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(399, 308, 183, 32);

        jButton3.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(46, 29, 101, 41);

        jLabel5.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 740, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected())
        {
            jComboBox1.setVisible(true);
            jRadioButton2.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         if(jRadioButton2.isSelected())
        {
            jComboBox1.setVisible(false);
            jRadioButton1.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setVisible(true);
        jRadioButton2.setVisible(true);
        jComboBox1.setVisible(true);
        jComboBox1.setSelectedIndex(0);
        jTextField1.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Citizen u= new Citizen(jTextField1.getText(), jPasswordField1.getText());
        String category="";
        
        if(jRadioButton2.isSelected())
        {
            category="citizen";
        }
        if(jRadioButton1.isSelected())
        {
        if(jComboBox1.getSelectedIndex()==1)
        {
            category="civil";
        }
        else if(jComboBox1.getSelectedIndex()==2)
        {
            category="criminal";
        }
        }
        
        int i=0;
        if(u.getUname().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter User Name!!");
            i++;
        }
        if(u.getPword().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter Password!!");
            i++;
        }
        if(jComboBox1.getSelectedIndex()==0 && jRadioButton2.isSelected()==false)
        {
            JOptionPane.showMessageDialog(this,"Select Division!!");
            i++;
        }
        if(jRadioButton1.isSelected()==false && jRadioButton2.isSelected()==false)
        {
             JOptionPane.showMessageDialog(this,"Select Category!!");
             i++;
        }
        
        
         if(i==0)
        {
         
            
                     if (u.getUname().equals("user") && u.getPword().equals("123"))        
                     {
                         if(category.equals("citizen"))
                         {
                             new COPENPAGE().setVisible(true);
                             this.dispose();
                         }
                         else if(category.equals("criminal"))
                         {
                             new CROPENPAGE().setVisible(true);
                             this.dispose();
                         }
                         else if(category.equals("civil"))
                         {
                             new CIOPENPAGE().setVisible(true);
                             this.dispose();
                         }
                     }
                   
                     else
                     {
                         JOptionPane.showMessageDialog(this, "Invalid Username Or Password!");
                     }
             
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new HOMEPAGE().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BLOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
